// Approximate public figures (acceptance rate, sticker tuition). Universities in
// Uzbekistan list no figures because they aren't published in a comparable way.
// Always double-check on the university's own admissions website.
type Uni = {
  name: string; country: string; city: string; lat: number; lng: number;
  acceptanceRate: number | null; tuition: number | null; requirements: string; aid: string; website: string; about: string;
};

const LOCAL_REQ = "Admission through the university's entrance exams and an English-language requirement; see the admissions page for this year's rules and dates.";

export const UNIVERSITIES: Uni[] = [
  { name: "Westminster International University in Tashkent", country: "Uzbekistan", city: "Tashkent", lat: 41.3121, lng: 69.2806, acceptanceRate: null, tuition: null, requirements: LOCAL_REQ, aid: "See the website for scholarships and state-funded places", website: "https://wiut.uz", about: "British-style degrees taught in English in partnership with the University of Westminster, London." },
  { name: "Inha University in Tashkent", country: "Uzbekistan", city: "Tashkent", lat: 41.3386, lng: 69.3346, acceptanceRate: null, tuition: null, requirements: LOCAL_REQ, aid: "See the website for scholarships and state-funded places", website: "https://inha.uz", about: "Engineering and IT university founded with Inha University in South Korea; teaching in English." },
  { name: "Turin Polytechnic University in Tashkent", country: "Uzbekistan", city: "Tashkent", lat: 41.3406, lng: 69.2135, acceptanceRate: null, tuition: null, requirements: LOCAL_REQ, aid: "See the website for scholarships and state-funded places", website: "https://polito.uz", about: "Engineering and architecture programmes developed with Politecnico di Torino, Italy." },
  { name: "National University of Uzbekistan", country: "Uzbekistan", city: "Tashkent", lat: 41.3496, lng: 69.2046, acceptanceRate: null, tuition: null, requirements: LOCAL_REQ, aid: "See the website for scholarships and state-funded places", website: "https://nuu.uz", about: "The country's leading classical university, with faculties across the sciences and humanities." },
  { name: "Tashkent State Technical University", country: "Uzbekistan", city: "Tashkent", lat: 41.3445, lng: 69.2051, acceptanceRate: null, tuition: null, requirements: LOCAL_REQ, aid: "See the website for scholarships and state-funded places", website: "https://tdtu.uz", about: "A major technical university for engineering, energy and technology." },
  { name: "Samarkand State University", country: "Uzbekistan", city: "Samarkand", lat: 39.6507, lng: 66.9606, acceptanceRate: null, tuition: null, requirements: LOCAL_REQ, aid: "See the website for scholarships and state-funded places", website: "https://samdu.uz", about: "One of the oldest universities in Central Asia, with strong natural sciences and humanities." },
  { name: "Massachusetts Institute of Technology", country: "USA", city: "Cambridge, MA", lat: 42.3601, lng: -71.0942, acceptanceRate: 4.5, tuition: 62000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://mitadmissions.org", about: "World leader in engineering, computer science and the physical sciences, known for hands-on research from the first year." },
  { name: "Harvard University", country: "USA", city: "Cambridge, MA", lat: 42.377, lng: -71.1167, acceptanceRate: 3.6, tuition: 59000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://college.harvard.edu", about: "The oldest university in the US, with a liberal-arts college, vast libraries and one of the largest financial-aid programs in the world." },
  { name: "Stanford University", country: "USA", city: "Stanford, CA", lat: 37.4275, lng: -122.1697, acceptanceRate: 3.9, tuition: 65000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admission.stanford.edu", about: "Silicon Valley's university: entrepreneurship, computer science and interdisciplinary research on a huge campus." },
  { name: "Princeton University", country: "USA", city: "Princeton, NJ", lat: 40.3431, lng: -74.6551, acceptanceRate: 4.5, tuition: 62000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://admission.princeton.edu", about: "Undergraduate-focused research university with a senior thesis for every student and no-loan financial aid." },
  { name: "Yale University", country: "USA", city: "New Haven, CT", lat: 41.3163, lng: -72.9223, acceptanceRate: 4.6, tuition: 67000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://admissions.yale.edu", about: "Residential-college system, strong humanities and a flexible liberal-arts curriculum." },
  { name: "California Institute of Technology", country: "USA", city: "Pasadena, CA", lat: 34.1377, lng: -118.1253, acceptanceRate: 3.0, tuition: 63000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://www.admissions.caltech.edu", about: "A tiny, intense science and engineering school that manages NASA's Jet Propulsion Laboratory." },
  { name: "University of Chicago", country: "USA", city: "Chicago, IL", lat: 41.7886, lng: -87.5987, acceptanceRate: 5.0, tuition: 67000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://collegeadmissions.uchicago.edu", about: "Famous for its rigorous Core curriculum, economics and quirky application essays." },
  { name: "University of Pennsylvania", country: "USA", city: "Philadelphia, PA", lat: 39.9522, lng: -75.1932, acceptanceRate: 5.4, tuition: 66000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.upenn.edu", about: "Home of Wharton, combining pre-professional programs with Ivy League liberal arts." },
  { name: "Columbia University", country: "USA", city: "New York, NY", lat: 40.8075, lng: -73.9626, acceptanceRate: 3.9, tuition: 69000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://undergrad.admissions.columbia.edu", about: "An Ivy League university in Manhattan with the famous Core Curriculum." },
  { name: "Duke University", country: "USA", city: "Durham, NC", lat: 36.0014, lng: -78.9382, acceptanceRate: 6.0, tuition: 66000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.duke.edu", about: "Top research university with strong medicine, public policy and a vibrant campus spirit." },
  { name: "Brown University", country: "USA", city: "Providence, RI", lat: 41.8268, lng: -71.4025, acceptanceRate: 5.2, tuition: 68000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Generous need-based aid for internationals", website: "https://admission.brown.edu", about: "Known for its Open Curriculum — no general-education requirements." },
  { name: "Johns Hopkins University", country: "USA", city: "Baltimore, MD", lat: 39.3299, lng: -76.6205, acceptanceRate: 6.5, tuition: 63000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://apply.jhu.edu", about: "America's first research university, a powerhouse in medicine, public health and engineering." },
  { name: "Northwestern University", country: "USA", city: "Evanston, IL", lat: 42.0565, lng: -87.6753, acceptanceRate: 7.0, tuition: 65000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.northwestern.edu", about: "Excellent journalism, engineering and economics on the shore of Lake Michigan." },
  { name: "Dartmouth College", country: "USA", city: "Hanover, NH", lat: 43.7044, lng: -72.2887, acceptanceRate: 5.3, tuition: 66000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://admissions.dartmouth.edu", about: "A close-knit Ivy with a flexible quarter system and strong undergraduate teaching." },
  { name: "Cornell University", country: "USA", city: "Ithaca, NY", lat: 42.4534, lng: -76.4735, acceptanceRate: 7.9, tuition: 67000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.cornell.edu", about: "The largest Ivy, with seven undergraduate colleges from engineering to hotel administration." },
  { name: "Carnegie Mellon University", country: "USA", city: "Pittsburgh, PA", lat: 40.4433, lng: -79.9436, acceptanceRate: 11.0, tuition: 64000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Limited need-based aid for internationals", website: "https://admission.enrollment.cmu.edu", about: "World-class computer science, robotics and drama under one roof." },
  { name: "Rice University", country: "USA", city: "Houston, TX", lat: 29.7174, lng: -95.4018, acceptanceRate: 8.0, tuition: 60000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admission.rice.edu", about: "A small research university with a residential-college system and strong STEM programs." },
  { name: "Vanderbilt University", country: "USA", city: "Nashville, TN", lat: 36.1447, lng: -86.8027, acceptanceRate: 5.6, tuition: 65000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.vanderbilt.edu", about: "Strong education, medicine and engineering with a collaborative student culture." },
  { name: "Washington University in St. Louis", country: "USA", city: "St. Louis, MO", lat: 38.6488, lng: -90.3108, acceptanceRate: 12.0, tuition: 65000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.wustl.edu", about: "Research-intensive with top programs in medicine, biology and architecture." },
  { name: "University of Notre Dame", country: "USA", city: "Notre Dame, IN", lat: 41.7052, lng: -86.2353, acceptanceRate: 12.0, tuition: 64000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-aware; meets full demonstrated need", website: "https://admissions.nd.edu", about: "A Catholic research university with a famous campus community and business school." },
  { name: "Georgia Institute of Technology", country: "USA", city: "Atlanta, GA", lat: 33.7756, lng: -84.3963, acceptanceRate: 16.0, tuition: 33000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Limited aid for internationals", website: "https://admission.gatech.edu", about: "A public tech powerhouse with some of the best-value engineering degrees in the US." },
  { name: "University of Michigan", country: "USA", city: "Ann Arbor, MI", lat: 42.278, lng: -83.7382, acceptanceRate: 18.0, tuition: 60000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Limited aid for internationals", website: "https://admissions.umich.edu", about: "A flagship public university with strength in nearly every field and huge school spirit." },
  { name: "New York University", country: "USA", city: "New York, NY", lat: 40.7295, lng: -73.9965, acceptanceRate: 8.0, tuition: 60000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Limited aid for internationals", website: "https://www.nyu.edu/admissions", about: "A global network university in Greenwich Village with campuses around the world." },
  { name: "NYU Abu Dhabi", country: "UAE", city: "Abu Dhabi", lat: 24.5236, lng: 54.4348, acceptanceRate: 4.0, tuition: 58000, requirements: "Holistic admission: strong academic record, essays, recommendations and English proficiency. Admitted students are invited to candidate weekends.", aid: "Meets full demonstrated need for all admitted students", website: "https://nyuad.nyu.edu", about: "A liberal-arts research campus with students from 120+ countries and exceptional aid." },
  { name: "Amherst College", country: "USA", city: "Amherst, MA", lat: 42.3709, lng: -72.517, acceptanceRate: 9.0, tuition: 68000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://www.amherst.edu/admission", about: "A top liberal-arts college with an open curriculum and small seminar classes." },
  { name: "Bowdoin College", country: "USA", city: "Brunswick, ME", lat: 43.9076, lng: -69.9637, acceptanceRate: 7.0, tuition: 66000, requirements: "Highly selective. Strong school grades, essays, recommendations and extracurriculars; English proficiency (TOEFL/IELTS/Duolingo) for international applicants. Check the current standardized-test policy.", aid: "Need-blind for international applicants", website: "https://www.bowdoin.edu/admissions", about: "A coastal liberal-arts college known for close faculty mentorship." },
  { name: "University of Oxford", country: "UK", city: "Oxford", lat: 51.7548, lng: -1.2544, acceptanceRate: 15.0, tuition: 45000, requirements: "Excellent grades in A-levels, the IB or equivalent qualifications (often plus a foundation year), a personal statement, and English proficiency such as IELTS 7.0+. Some courses require admissions tests or interviews.", aid: "Scholarships for some international students", website: "https://www.ox.ac.uk/admissions", about: "The oldest university in the English-speaking world, built around tutorial teaching in colleges." },
  { name: "University of Cambridge", country: "UK", city: "Cambridge", lat: 52.2043, lng: 0.1149, acceptanceRate: 18.0, tuition: 45000, requirements: "Excellent grades in A-levels, the IB or equivalent qualifications (often plus a foundation year), a personal statement, and English proficiency such as IELTS 7.0+. Some courses require admissions tests or interviews.", aid: "Scholarships for some international students", website: "https://www.undergraduate.study.cam.ac.uk", about: "Supervision-based teaching in 31 colleges; world-leading in maths and the sciences." },
  { name: "National University of Singapore", country: "Singapore", city: "Singapore", lat: 1.2966, lng: 103.7764, acceptanceRate: 8.0, tuition: 30000, requirements: "Strong national qualifications, A-levels or IB, plus English proficiency; some programmes require interviews or aptitude tests.", aid: "Tuition grants and scholarships available", website: "https://www.nus.edu.sg/oam", about: "Asia's top-ranked university with strong engineering, computing and business." },
];
